#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu5320
    username: user-ins
    password: "$6$rounds=4096$abcdefghijk..."
  locale: pt_BR
  keyboard:
    layout: br
  disk_setup:
    /dev/sda1:
      table_type: gpt
      layout:
        - 100%
      overwrite: false
  user-data:
    users:
      - name: user-ins
        gecos: "user-ins"
        groups: [sudo]
        shell: /bin/bash
        passwd: "$6$rounds=4096$abcdefghijk..."
    bootcmd:
      - apt-get update
      - apt-get install -y cryptsetup
      - echo "Habilitando a criptografia do disco..."
      - cryptsetup luksFormat /dev/sda1 --key-file /etc/secure-keyfile
      - cryptsetup open /dev/sda1 disco_criptografado --key-file /etc/secure-keyfile
      - echo "Atualizando pacotes do sistema..."
      - apt-get upgrade -y
      - echo "Instalando htop..."
      - apt-get install -y htop
      - echo "Instalando Puppet..."
      - wget https://apt.puppetlabs.com/puppet8-release-noble.deb
      - dpkg -i puppet8-release-noble.deb
      - apt-get update
      - apt-get install -y puppet-agent
    write_files:
      - path: /etc/secure-keyfile
        permissions: '0600'
        content: troca essa senha
